on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
  schedule:
  - cron: "*/5 * * * *"

permissions: 
  contents: write

jobs:
   run-script:
     name: Fetch data
     runs-on: ubuntu-latest
     steps:
        - name: Check out repository code
          uses: actions/checkout@v3

        - name: Set git identity
          run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
          
        - name: Ensure data directory exists
          run: |
            mkdir -p data
                
        - name: Fetch emergency data
          run: |
            curl 'https://adsb.oarc.uk/emergencies/emergencies.json?search=' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'Referer: https://adsb.oarc.uk/emergencies/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' | jq '.' --indent 4 > data/emergencies.json
                            
        - name: Fetch historical emergency data
          run: |
            curl 'https://adsb.oarc.uk/emergencies/emergencies_history.json?search=' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'Referer: https://adsb.oarc.uk/emergencies/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' | jq '.' --indent 4 > data/emergencies_history.json
            
        - name: File Listing
          run: |
            ls -R

        - name: Git Status
          run: |
            git status
            
        - name: Add data to git
          run: |
            git add data
            
        - name: Commit to git
          run: |
            git commit -m "Update data" || echo "No changes to commit"
            
        - name: Git Status
          run: |
            git status
            
        - name: Git Push
          run: |
            git status
            git push
            
        - name: Git Status
          run: |
            git status
